// Generated directly from C by cpp_transpiler.
vp8_set_reference_value_in_ethreading :: (args: *Va_List_Tag) -> *Ref_Frame_T {
    return c_transpiler_va_arg(cast(*void) (args), *Ref_Frame_T);
}

vp8_copy_reference_value_in_ethreading :: (args: *Va_List_Tag) -> *Ref_Frame_T {
    return c_transpiler_va_arg(cast(*void) (args), *Ref_Frame_T);
}

vp8_set_postproc_value_in_ethreading :: (args: *Va_List_Tag) -> *Vp8_Postproc_Cfg_T {
    return c_transpiler_va_arg(cast(*void) (args), *Vp8_Postproc_Cfg_T);
}

vp9_get_reference_value_in_ethreading :: (args: *Va_List_Tag) -> *Vp9_Ref_Frame_T {
    return c_transpiler_va_arg(cast(*void) (args), *Vp9_Ref_Frame_T);
}

vp8_e_set_roi_map_value_in_ethreading :: (args: *Va_List_Tag) -> *Roi_Map_T {
    return c_transpiler_va_arg(cast(*void) (args), *Roi_Map_T);
}

vp8_e_set_activemap_value_in_ethreading :: (args: *Va_List_Tag) -> *Active_Map_T {
    return c_transpiler_va_arg(cast(*void) (args), *Active_Map_T);
}

vp8_e_set_scalemode_value_in_ethreading :: (args: *Va_List_Tag) -> *Scaling_Mode_T {
    return c_transpiler_va_arg(cast(*void) (args), *Scaling_Mode_T);
}

vp8_e_set_cpuused_value_in_ethreading :: (args: *Va_List_Tag) -> s32 {
    return c_transpiler_va_arg(cast(*void) (args), s32);
}

vp8_e_set_enableautoaltref_value_in_ethreading :: (args: *Va_List_Tag) -> u32 {
    return c_transpiler_va_arg(cast(*void) (args), u32);
}

vp8_e_set_noise_sensitivity_value_in_ethreading :: (args: *Va_List_Tag) -> u32 {
    return c_transpiler_va_arg(cast(*void) (args), u32);
}

vp8_e_set_sharpness_value_in_ethreading :: (args: *Va_List_Tag) -> u32 {
    return c_transpiler_va_arg(cast(*void) (args), u32);
}

vp8_e_set_static_threshold_value_in_ethreading :: (args: *Va_List_Tag) -> u32 {
    return c_transpiler_va_arg(cast(*void) (args), u32);
}

vp8_e_set_token_partitions_value_in_ethreading :: (args: *Va_List_Tag) -> s32 {
    return c_transpiler_va_arg(cast(*void) (args), s32);
}

vp8_e_get_last_quantizer_value_in_ethreading :: (args: *Va_List_Tag) -> *s32 {
    return c_transpiler_va_arg(cast(*void) (args), *s32);
}

vp8_e_get_last_quantizer_64_value_in_ethreading :: (args: *Va_List_Tag) -> *s32 {
    return c_transpiler_va_arg(cast(*void) (args), *s32);
}

vp8_e_set_arnr_maxframes_value_in_ethreading :: (args: *Va_List_Tag) -> u32 {
    return c_transpiler_va_arg(cast(*void) (args), u32);
}

vp8_e_set_arnr_strength_value_in_ethreading :: (args: *Va_List_Tag) -> u32 {
    return c_transpiler_va_arg(cast(*void) (args), u32);
}

vp8_e_set_arnr_type_value_in_ethreading :: (args: *Va_List_Tag) -> u32 {
    return c_transpiler_va_arg(cast(*void) (args), u32);
}

vp8_e_set_tuning_value_in_ethreading :: (args: *Va_List_Tag) -> s32 {
    return c_transpiler_va_arg(cast(*void) (args), s32);
}

vp8_e_set_cq_level_value_in_ethreading :: (args: *Va_List_Tag) -> u32 {
    return c_transpiler_va_arg(cast(*void) (args), u32);
}

vp8_e_set_max_intra_bitrate_pct_value_in_ethreading :: (args: *Va_List_Tag) -> u32 {
    return c_transpiler_va_arg(cast(*void) (args), u32);
}

vp8_e_set_frame_flags_value_in_ethreading :: (args: *Va_List_Tag) -> s32 {
    return c_transpiler_va_arg(cast(*void) (args), s32);
}

vp9_e_set_max_inter_bitrate_pct_value_in_ethreading :: (args: *Va_List_Tag) -> u32 {
    return c_transpiler_va_arg(cast(*void) (args), u32);
}

vp9_e_set_gf_cbr_boost_pct_value_in_ethreading :: (args: *Va_List_Tag) -> u32 {
    return c_transpiler_va_arg(cast(*void) (args), u32);
}

vp8_e_set_temporal_layer_id_value_in_ethreading :: (args: *Va_List_Tag) -> s32 {
    return c_transpiler_va_arg(cast(*void) (args), s32);
}

vp8_e_set_screen_content_mode_value_in_ethreading :: (args: *Va_List_Tag) -> u32 {
    return c_transpiler_va_arg(cast(*void) (args), u32);
}

vp9_e_set_lossless_value_in_ethreading :: (args: *Va_List_Tag) -> u32 {
    return c_transpiler_va_arg(cast(*void) (args), u32);
}

vp9_e_set_tile_columns_value_in_ethreading :: (args: *Va_List_Tag) -> s32 {
    return c_transpiler_va_arg(cast(*void) (args), s32);
}

vp9_e_set_tile_rows_value_in_ethreading :: (args: *Va_List_Tag) -> s32 {
    return c_transpiler_va_arg(cast(*void) (args), s32);
}

vp9_e_set_frame_parallel_decoding_value_in_ethreading :: (args: *Va_List_Tag) -> u32 {
    return c_transpiler_va_arg(cast(*void) (args), u32);
}

vp9_e_set_aq_mode_value_in_ethreading :: (args: *Va_List_Tag) -> u32 {
    return c_transpiler_va_arg(cast(*void) (args), u32);
}

vp9_e_set_frame_periodic_boost_value_in_ethreading :: (args: *Va_List_Tag) -> u32 {
    return c_transpiler_va_arg(cast(*void) (args), u32);
}

vp9_e_set_noise_sensitivity_value_in_ethreading :: (args: *Va_List_Tag) -> u32 {
    return c_transpiler_va_arg(cast(*void) (args), u32);
}

vp9_e_set_svc_value_in_ethreading :: (args: *Va_List_Tag) -> s32 {
    return c_transpiler_va_arg(cast(*void) (args), s32);
}

vp9_e_set_roi_map_value_in_ethreading :: (args: *Va_List_Tag) -> *Roi_Map_T {
    return c_transpiler_va_arg(cast(*void) (args), *Roi_Map_T);
}

vp9_e_set_svc_parameters_value_in_ethreading :: (args: *Va_List_Tag) -> *void {
    return c_transpiler_va_arg(cast(*void) (args), *void);
}

vp9_e_set_svc_layer_id_value_in_ethreading :: (args: *Va_List_Tag) -> *Svc_Layer_Id_T {
    return c_transpiler_va_arg(cast(*void) (args), *Svc_Layer_Id_T);
}

vp9_e_set_tune_content_value_in_ethreading :: (args: *Va_List_Tag) -> s32 {
    return c_transpiler_va_arg(cast(*void) (args), s32);
}

vp9_e_get_svc_layer_id_value_in_ethreading :: (args: *Va_List_Tag) -> *Svc_Layer_Id_T {
    return c_transpiler_va_arg(cast(*void) (args), *Svc_Layer_Id_T);
}

vp9_e_register_cx_callback_value_in_ethreading :: (args: *Va_List_Tag) -> *void {
    return c_transpiler_va_arg(cast(*void) (args), *void);
}

vp9_e_set_color_space_value_in_ethreading :: (args: *Va_List_Tag) -> s32 {
    return c_transpiler_va_arg(cast(*void) (args), s32);
}

vp9_e_set_min_gf_interval_value_in_ethreading :: (args: *Va_List_Tag) -> u32 {
    return c_transpiler_va_arg(cast(*void) (args), u32);
}

vp9_e_set_max_gf_interval_value_in_ethreading :: (args: *Va_List_Tag) -> u32 {
    return c_transpiler_va_arg(cast(*void) (args), u32);
}

vp9_e_get_activemap_value_in_ethreading :: (args: *Va_List_Tag) -> *Active_Map_T {
    return c_transpiler_va_arg(cast(*void) (args), *Active_Map_T);
}

vp9_e_set_color_range_value_in_ethreading :: (args: *Va_List_Tag) -> s32 {
    return c_transpiler_va_arg(cast(*void) (args), s32);
}

vp9_e_set_svc_ref_frame_config_value_in_ethreading :: (args: *Va_List_Tag) -> *Svc_Ref_Frame_Config_T {
    return c_transpiler_va_arg(cast(*void) (args), *Svc_Ref_Frame_Config_T);
}

vp9_e_set_render_size_value_in_ethreading :: (args: *Va_List_Tag) -> *s32 {
    return c_transpiler_va_arg(cast(*void) (args), *s32);
}

vp9_e_set_target_level_value_in_ethreading :: (args: *Va_List_Tag) -> u32 {
    return c_transpiler_va_arg(cast(*void) (args), u32);
}

vp9_e_set_row_mt_value_in_ethreading :: (args: *Va_List_Tag) -> u32 {
    return c_transpiler_va_arg(cast(*void) (args), u32);
}

vp9_e_get_level_value_in_ethreading :: (args: *Va_List_Tag) -> *s32 {
    return c_transpiler_va_arg(cast(*void) (args), *s32);
}

vp9_e_set_alt_ref_aq_value_in_ethreading :: (args: *Va_List_Tag) -> s32 {
    return c_transpiler_va_arg(cast(*void) (args), s32);
}

vp8_e_set_gf_cbr_boost_pct_value_in_ethreading :: (args: *Va_List_Tag) -> u32 {
    return c_transpiler_va_arg(cast(*void) (args), u32);
}

vp9_e_enable_motion_vector_unit_test_value_in_ethreading :: (args: *Va_List_Tag) -> u32 {
    return c_transpiler_va_arg(cast(*void) (args), u32);
}

vp9_e_set_svc_inter_layer_pred_value_in_ethreading :: (args: *Va_List_Tag) -> u32 {
    return c_transpiler_va_arg(cast(*void) (args), u32);
}

vp9_e_set_svc_frame_drop_layer_value_in_ethreading :: (args: *Va_List_Tag) -> *Svc_Frame_Drop_T {
    return c_transpiler_va_arg(cast(*void) (args), *Svc_Frame_Drop_T);
}

vp9_e_get_svc_ref_frame_config_value_in_ethreading :: (args: *Va_List_Tag) -> *Svc_Ref_Frame_Config_T {
    return c_transpiler_va_arg(cast(*void) (args), *Svc_Ref_Frame_Config_T);
}

vp9_e_set_svc_gf_temporal_ref_value_in_ethreading :: (args: *Va_List_Tag) -> u32 {
    return c_transpiler_va_arg(cast(*void) (args), u32);
}

vp9_e_set_svc_spatial_layer_sync_value_in_ethreading :: (args: *Va_List_Tag) -> *Svc_Spatial_Layer_Sync_T {
    return c_transpiler_va_arg(cast(*void) (args), *Svc_Spatial_Layer_Sync_T);
}

vp9_e_set_tpl_value_in_ethreading :: (args: *Va_List_Tag) -> s32 {
    return c_transpiler_va_arg(cast(*void) (args), s32);
}

vp9_e_set_postencode_drop_value_in_ethreading :: (args: *Va_List_Tag) -> u32 {
    return c_transpiler_va_arg(cast(*void) (args), u32);
}

vp9_e_set_delta_q_uv_value_in_ethreading :: (args: *Va_List_Tag) -> s32 {
    return c_transpiler_va_arg(cast(*void) (args), s32);
}

vp9_e_set_disable_overshoot_maxq_cbr_value_in_ethreading :: (args: *Va_List_Tag) -> s32 {
    return c_transpiler_va_arg(cast(*void) (args), s32);
}

vp9_e_set_disable_loopfilter_value_in_ethreading :: (args: *Va_List_Tag) -> s32 {
    return c_transpiler_va_arg(cast(*void) (args), s32);
}

vp9_e_set_external_rate_control_value_in_ethreading :: (args: *Va_List_Tag) -> *Rc_Funcs_T {
    return c_transpiler_va_arg(cast(*void) (args), *Rc_Funcs_T);
}

vp9_e_set_rtc_external_ratectrl_value_in_ethreading :: (args: *Va_List_Tag) -> s32 {
    return c_transpiler_va_arg(cast(*void) (args), s32);
}

vp9_e_get_loopfilter_level_value_in_ethreading :: (args: *Va_List_Tag) -> *s32 {
    return c_transpiler_va_arg(cast(*void) (args), *s32);
}

vp9_e_get_last_quantizer_svc_layers_value_in_ethreading :: (args: *Va_List_Tag) -> *s32 {
    return c_transpiler_va_arg(cast(*void) (args), *s32);
}

vp8_e_set_rtc_external_ratectrl_value_in_ethreading :: (args: *Va_List_Tag) -> s32 {
    return c_transpiler_va_arg(cast(*void) (args), s32);
}

vp9_e_set_quantizer_one_pass_value_in_ethreading :: (args: *Va_List_Tag) -> s32 {
    return c_transpiler_va_arg(cast(*void) (args), s32);
}

vp9_e_set_key_frame_filtering_value_in_ethreading :: (args: *Va_List_Tag) -> s32 {
    return c_transpiler_va_arg(cast(*void) (args), s32);
}

vp9_e_set_validate_hbd_input_value_in_ethreading :: (args: *Va_List_Tag) -> s32 {
    return c_transpiler_va_arg(cast(*void) (args), s32);
}

scale2_ratio_in_ethreading :: (mode: s32, hr: *s32, hs: *s32) {
    if mode == {
        case VP8E_NORMAL;
            hr.* = 1;
            hs.* = 1;
        case VP8E_FOURFIVE;
            hr.* = 4;
            hs.* = 5;
        case VP8E_THREEFIVE;
            hr.* = 3;
            hs.* = 5;
        case VP8E_ONETWO;
            hr.* = 1;
            hs.* = 2;
        case;
            hr.* = 1;
            hs.* = 1;
    }
}

validate_buffer_in_ethreading :: (start: *u8, len: u64, end: *u8, error: *Internal_Error_Info) -> s32 {
    if start + len > start && start + len < end {
        return 1;
    } else {
        internal_error(
            error,
            cast,no_check(Codec_Err_T) CODEC_CORRUPT_FRAME,
            c_string("Truncated packet or corrupt partition ")
        );
    }

    return 0;
}

vp8_encode_bool_in_ethreading :: (bc: *BOOL_CODER, bit: s32, probability: s32) {
    count := bc.count;
    range := bc.range;
    lowvalue := bc.lowvalue;

    split := 1 + ((range - 1) * cast,no_check(u32) probability) >> 8;

    range = split;

    if bit != 0 {
        lowvalue += split;
        range = bc.range - split;
    }

    shift := cast,no_check(s32) VP8_NORM[range];

    c_transpiler_compound_shl(*(range), (((cast,no_check(u32) shift) & 31)), u32, u32);
    count += shift;

    if count >= 0 {
        offset := shift - count;

        if lowvalue << (((offset - 1)) & 31) & 0x80000000 != 0 {
            x := cast,no_check(s32) (bc.pos - 1);

            while x >= 0 && bc.buffer[x] == 0xff {
                bc.buffer[x] = 0;
                x -= 1;
            }

            bc.buffer[x] = cast,no_check(u8) ((cast,no_check(s32) bc.buffer[x]) + 1);
        }

        validate_buffer_in_ethreading(bc.buffer + bc.pos, 1, bc.buffer_end, bc.error);
        bc.buffer[bc.pos] = cast,no_check(u8) (lowvalue >> (((24 - offset)) & 31) & 0xff);
        bc.pos += 1;

        shift = count;
        lowvalue =
            cast,no_check(u32) (cast,no_check(s32) ((cast,no_check(u64) lowvalue) << ((offset) & 63) & 0xffffff));
        count -= 8;
    }

    c_transpiler_compound_shl(*(lowvalue), (((cast,no_check(u32) shift) & 31)), u32, u32);
    bc.count = count;
    bc.lowvalue = lowvalue;
    bc.range = range;
}

vp8_cost_branch_in_ethreading :: (ct: *u32, p: Vp8_Prob) -> u32 {
    return cast,no_check(u32) ((((cast,no_check(u64) ct[0]) * cast(u64) VP8_PROB_COST[p]) + (cast,no_check(u64) ct[1]) * cast(u64) VP8_PROB_COST[255 - cast(s32) p]) >> 8);
}

vp8_treed_write_in_ethreading :: (W: *Vp8_Writer_in_treewriter, t: *Vp8_Tree_Index, P: *Vp8_Prob, v: s32, n: s32) {
    i: Vp8_Tree_Index = 0;

    while true {
        {
            B := v >> ((c_transpiler_pre_decrement(*(n))) & 31) & 1;
            vp8_encode_bool_in_ethreading(W, B, cast,no_check(s32) P[(cast(s32) i) >> 1]);
            i = t[(cast(s32) i) + B];
        }
        if n == 0 break;
    }
}

vp8_write_token_in_ethreading :: (W: *Vp8_Writer_in_treewriter, t: *Vp8_Tree_Index, P: *Vp8_Prob, X: *Vp8_Token) {
    vp8_treed_write_in_ethreading(W, t, P, X.value, X.len);
}

vp8_treed_cost_in_ethreading :: (t: *Vp8_Tree_Index, P: *Vp8_Prob, v: s32, n: s32) -> s32 {
    c: s32 = 0;
    i: Vp8_Tree_Index = 0;

    while true {
        {
            B := v >> ((c_transpiler_pre_decrement(*(n))) & 31) & 1;
            c_transpiler_compound_add(*(c), (VP8_PROB_COST[(ifx B != 0 then 255 - cast(s32) P[(cast(s32) i) >> 1] else cast,no_check(s32) P[(cast(s32) i) >> 1])]), u32, u32);
            i = t[(cast(s32) i) + B];
        }
        if n == 0 break;
    }

    return c;
}

vp8_cost_token_in_ethreading :: (t: *Vp8_Tree_Index, P: *Vp8_Prob, X: *Vp8_Token) -> s32 {
    return vp8_treed_cost_in_ethreading(t, P, X.value, X.len);
}

vp8_sem_wait_in_ethreading :: (sem: *Sem_T) -> s32 {
    ret: s32 = ---;
    while ((ifx true { assignment_0: s32 = cast,no_check(s32) (sem_wait(sem)); (ret) = assignment_0; assignment_0; }) == -1) && system_error_code().* == 4 {
    }
    return ret;
}

atomic_init_in_ethreading :: (atomic: *Atomic_Int, value: s32) {
    atomic.value = value;
}

atomic_store_release_in_ethreading :: (atomic: *Atomic_Int, value: s32) {
    c_transpiler_atomic_store(*atomic.value, value);
}

atomic_load_acquire_in_ethreading :: (atomic: *Atomic_Int) -> s32 {
    return atomic_load(*atomic.value);
}

vp8_atomic_spin_wait_in_ethreading :: (mb_col: s32, last_row_current_mb_col: *Atomic_Int, NSYNC: s32) {
    while mb_col > atomic_load_acquire_in_ethreading(last_row_current_mb_col) - NSYNC {
    }
}

mv_bias_in_ethreading :: (
    refmb_ref_frame_sign_bias: s32,
    refframe: s32,
    mvp: *Int_Mv_in_mv,
    ref_frame_sign_bias: *s32
) {
    if refmb_ref_frame_sign_bias != ref_frame_sign_bias[refframe] {
        mvp.as_mv.row = cast,no_check(s16) ((cast,no_check(s32) mvp.as_mv.row) * -1);
        mvp.as_mv.col = cast,no_check(s16) ((cast,no_check(s32) mvp.as_mv.col) * -1);
    }
}

vp8_clamp_mv2_in_ethreading :: (mv: *Int_Mv_in_mv, xd: *MACROBLOCKD_in_blockd) {
    if cast,no_check(s32) mv.as_mv.col < xd.mb_to_left_edge - (cast(s32) 16) << 3 {
        mv.as_mv.col = cast,no_check(s16) (xd.mb_to_left_edge - (cast(s32) 16) << 3);
    } else if cast,no_check(s32) mv.as_mv.col > xd.mb_to_right_edge + (cast(s32) 16) << 3 {
        mv.as_mv.col = cast,no_check(s16) (xd.mb_to_right_edge + (cast(s32) 16) << 3);
    }

    if cast,no_check(s32) mv.as_mv.row < xd.mb_to_top_edge - (cast(s32) 16) << 3 {
        mv.as_mv.row = cast,no_check(s16) (xd.mb_to_top_edge - (cast(s32) 16) << 3);
    } else if cast,no_check(s32) mv.as_mv.row > xd.mb_to_bottom_edge + (cast(s32) 16) << 3 {
        mv.as_mv.row = cast,no_check(s16) (xd.mb_to_bottom_edge + (cast(s32) 16) << 3);
    }
}

vp8_clamp_mv_in_ethreading :: (
    mv: *Int_Mv_in_mv,
    mb_to_left_edge: s32,
    mb_to_right_edge: s32,
    mb_to_top_edge: s32,
    mb_to_bottom_edge: s32
) {
    mv.as_mv.col =
        cast,no_check(s16) ((ifx cast,no_check(s32) mv.as_mv.col < mb_to_left_edge then mb_to_left_edge else cast,no_check(s32) mv.as_mv.col));
    mv.as_mv.col =
        cast,no_check(s16) ((ifx cast,no_check(s32) mv.as_mv.col > mb_to_right_edge then mb_to_right_edge else cast,no_check(s32) mv.as_mv.col));
    mv.as_mv.row =
        cast,no_check(s16) ((ifx cast,no_check(s32) mv.as_mv.row < mb_to_top_edge then mb_to_top_edge else cast,no_check(s32) mv.as_mv.row));
    mv.as_mv.row =
        cast,no_check(s16) ((ifx cast,no_check(s32) mv.as_mv.row > mb_to_bottom_edge then mb_to_bottom_edge else cast,no_check(s32) mv.as_mv.row));
}

vp8_check_mv_bounds_in_ethreading :: (
    mv: *Int_Mv_in_mv,
    mb_to_left_edge: s32,
    mb_to_right_edge: s32,
    mb_to_top_edge: s32,
    mb_to_bottom_edge: s32
) -> u32 {
    need_to_clamp := cast(u32) (cast,no_check(s32) mv.as_mv.col < mb_to_left_edge);
    need_to_clamp |= cast(u32) (cast,no_check(s32) mv.as_mv.col > mb_to_right_edge);
    need_to_clamp |= cast(u32) (cast,no_check(s32) mv.as_mv.row < mb_to_top_edge);
    need_to_clamp |= cast(u32) (cast,no_check(s32) mv.as_mv.row > mb_to_bottom_edge);
    return need_to_clamp;
}

left_block_mv_in_ethreading :: (cur_mb: *MODE_INFO_in_blockd, b: s32) -> u32 {
    if b & 3 == 0 {
        cur_mb -= 1;

        if cur_mb.mbmi.mode != cast,no_check(u8) SPLITMV {
            return cur_mb.mbmi.mv.as_int;
        }
        b += 4;
    }

    return (((cur_mb.bmi.data + b - 1)).mv).as_int;
}

above_block_mv_in_ethreading :: (cur_mb: *MODE_INFO_in_blockd, b: s32, mi_stride: s32) -> u32 {
    if b >> 2 == 0 {
        cur_mb -= mi_stride;

        if cur_mb.mbmi.mode != cast,no_check(u8) SPLITMV {
            return cur_mb.mbmi.mv.as_int;
        }
        b += 16;
    }

    return (((cur_mb.bmi.data + (b - 4))).mv).as_int;
}

left_block_mode_in_ethreading :: (cur_mb: *MODE_INFO_in_blockd, b: s32) -> B_PREDICTION_MODE {
    if b & 3 == 0 {
        cur_mb -= 1;
        if cast,no_check(s32) cur_mb.mbmi.mode == {
            case B_PRED;
                return ((cur_mb.bmi.data + b + 3)).as_mode;
            case DC_PRED;
                return cast,no_check(B_PREDICTION_MODE) B_DC_PRED;
            case V_PRED;
                return cast,no_check(B_PREDICTION_MODE) B_VE_PRED;
            case H_PRED;
                return cast,no_check(B_PREDICTION_MODE) B_HE_PRED;
            case TM_PRED;
                return cast,no_check(B_PREDICTION_MODE) B_TM_PRED;
            case;
                return cast,no_check(B_PREDICTION_MODE) B_DC_PRED;
        }
    }

    return ((cur_mb.bmi.data + b - 1)).as_mode;
}

above_block_mode_in_ethreading :: (cur_mb: *MODE_INFO_in_blockd, b: s32, mi_stride: s32) -> B_PREDICTION_MODE {
    if b >> 2 == 0 {
        cur_mb -= mi_stride;

        if cast,no_check(s32) cur_mb.mbmi.mode == {
            case B_PRED;
                return ((cur_mb.bmi.data + b + 12)).as_mode;
            case DC_PRED;
                return cast,no_check(B_PREDICTION_MODE) B_DC_PRED;
            case V_PRED;
                return cast,no_check(B_PREDICTION_MODE) B_VE_PRED;
            case H_PRED;
                return cast,no_check(B_PREDICTION_MODE) B_HE_PRED;
            case TM_PRED;
                return cast,no_check(B_PREDICTION_MODE) B_TM_PRED;
            case;
                return cast,no_check(B_PREDICTION_MODE) B_DC_PRED;
        }
    }

    return ((cur_mb.bmi.data + b - 4)).as_mode;
}

vp8cx_init_mbrthread_data :: (cpi: *VP8_COMP, x: *MACROBLOCK_in_block, mbr_ei: *MB_ROW_COMP, count: s32) {
    CM := *cpi.common;
    XD := *x.e_mbd;

    if 0 < count {
        for i: 0..count - 1 {
            mb := *mbr_ei[i].mb;
            mbd := *mb.e_mbd;

            mbd.subpixel_predict = XD.subpixel_predict;
            mbd.subpixel_predict8x4 = XD.subpixel_predict8x4;
            mbd.subpixel_predict8x8 = XD.subpixel_predict8x8;
            mbd.subpixel_predict16x16 = XD.subpixel_predict16x16;
            mb.gf_active_ptr = x.gf_active_ptr;

            fill_memory(mbr_ei[i].segment_counts.data, 0, 4 * cast(u64) size_of(s32));
            mbr_ei[i].totalrate = 0;

            mb.partition_info = x.pi + x.e_mbd.mode_info_stride * (i + 1);

            mbd.frame_type = CM.frame_type;

            mb.src = cpi.source.*;
            mbd.pre = CM.yv12_fb[CM.lst_fb_idx];
            mbd.dst = CM.yv12_fb[CM.new_fb_idx];

            mb.src.y_buffer += 16 * x.src.y_stride * (i + 1);
            mb.src.u_buffer += 8 * x.src.uv_stride * (i + 1);
            mb.src.v_buffer += 8 * x.src.uv_stride * (i + 1);

            vp8_build_block_offsets(mb);

            mbd.left_context = *CM.left_context;
            mb.mvc = CM.fc.mvc.data;

            setup_mbby_copy(*mbr_ei[i].mb, x);

            mbd.fullpixel_mask = ~(cast(s32) 0);
            if CM.full_pixel != 0 {
                mbd.fullpixel_mask = ~(cast(s32) 7);
            }

            fill_memory(*mb.coef_counts, 0, mb.coef_counts.count * size_of([8] [3] [12] u32));
            fill_memory(*x.ymode_count, 0, x.ymode_count.count * size_of(s32));
            mb.skip_true_count = 0;
            fill_memory(*mb.m_vcount, 0, mb.m_vcount.count * size_of([2047] u32));
            mb.prediction_error = 0;
            mb.intra_error = 0;
            fill_memory(*mb.count_mb_ref_frame_usage, 0, mb.count_mb_ref_frame_usage.count * size_of(s32));
            mb.mbs_tested_so_far = 0;
            mb.mbs_zero_last_dot_suppress = 0;
        }
    }
}

setup_mbby_copy :: (mbdst: *MACROBLOCK_in_block, mbsrc: *MACROBLOCK_in_block) {
    x := mbsrc;
    z := mbdst;

    z.ss = x.ss;
    z.ss_count = x.ss_count;
    z.searches_per_step = x.searches_per_step;
    z.errorperbit = x.errorperbit;

    z.sadperbit16 = x.sadperbit16;
    z.sadperbit4 = x.sadperbit4;

    z.short_fdct4x4 = x.short_fdct4x4;
    z.short_fdct8x4 = x.short_fdct8x4;
    z.short_walsh4x4 = x.short_walsh4x4;
    z.quantize_b = x.quantize_b;
    z.optimize = x.optimize;

    z.mvcost[0] = x.mvcost[0];
    z.mvcost[1] = x.mvcost[1];
    z.mvsadcost[0] = x.mvsadcost[0];
    z.mvsadcost[1] = x.mvsadcost[1];

    z.token_costs = x.token_costs;
    z.inter_bmode_costs = x.inter_bmode_costs;
    z.mbmode_cost = x.mbmode_cost;
    z.intra_uv_mode_cost = x.intra_uv_mode_cost;
    z.bmode_costs = x.bmode_costs;

    for i: 0..cast(s32) 25 - 1 {
        z.block[i].quant = x.block[i].quant;
        z.block[i].quant_fast = x.block[i].quant_fast;
        z.block[i].quant_shift = x.block[i].quant_shift;
        z.block[i].zbin = x.block[i].zbin;
        z.block[i].zrun_zbin_boost = x.block[i].zrun_zbin_boost;
        z.block[i].round = x.block[i].round;
        z.block[i].src_stride = x.block[i].src_stride;
    }

    z.q_index = x.q_index;
    z.act_zbin_adj = x.act_zbin_adj;
    z.last_act_zbin_adj = x.last_act_zbin_adj;

    {
        xd := *x.e_mbd;
        zd := *z.e_mbd;

        zd.subpixel_predict = xd.subpixel_predict;
        zd.subpixel_predict8x4 = xd.subpixel_predict8x4;
        zd.subpixel_predict8x8 = xd.subpixel_predict8x8;
        zd.subpixel_predict16x16 = xd.subpixel_predict16x16;
        zd.segmentation_enabled = xd.segmentation_enabled;
        zd.mb_segment_abs_delta = xd.mb_segment_abs_delta;
        copy_memory(
            zd.segment_feature_data.data,
            xd.segment_feature_data.data,
            xd.segment_feature_data.count * size_of([4] s8)
        );

        copy_memory(zd.dequant_y1_dc.data, xd.dequant_y1_dc.data, xd.dequant_y1_dc.count * size_of(s16));
        copy_memory(zd.dequant_y1.data, xd.dequant_y1.data, xd.dequant_y1.count * size_of(s16));
        copy_memory(zd.dequant_y2.data, xd.dequant_y2.data, xd.dequant_y2.count * size_of(s16));
        copy_memory(zd.dequant_uv.data, xd.dequant_uv.data, xd.dequant_uv.count * size_of(s16));

        for i: 0..cast(s32) 16 - 1 {
            zd.block[i].dequant = zd.dequant_y1.data;
        }
        if 16 < 24 {
            for i: 16..cast(s32) 24 - 1 {
                zd.block[i].dequant = zd.dequant_uv.data;
            }
        }
        zd.block[24].dequant = zd.dequant_y2.data;

        copy_memory(z.rd_threshes.data, x.rd_threshes.data, x.rd_threshes.count * size_of(s32));
        copy_memory(z.rd_thresh_mult.data, x.rd_thresh_mult.data, x.rd_thresh_mult.count * size_of(s32));

        z.zbin_over_quant = x.zbin_over_quant;
        z.zbin_mode_boost_enabled = x.zbin_mode_boost_enabled;
        z.zbin_mode_boost = x.zbin_mode_boost;

        fill_memory(z.error_bins.data, 0, z.error_bins.count * size_of(s32));
    }
}

vp8cx_create_encoder_threads :: (cpi: *VP8_COMP) -> s32 {
    cm := *cpi.common;
    th_count: s32 = 0;

    if cm.processor_core_count > 1 && cpi.oxcf.multi_threaded > 1 {
        th_count = cpi.oxcf.multi_threaded - 1;

        if cpi.oxcf.multi_threaded > cm.processor_core_count {
            th_count = cm.processor_core_count - 1;
        }

        if th_count > cm.mb_cols / cpi.mt_sync_range - 1 {
            th_count = cm.mb_cols / cpi.mt_sync_range - 1;
        }
    }
    if th_count == cpi.encoding_thread_count {
        return 0;
    }

    vp8cx_remove_encoder_threads(cpi);
    if th_count != 0 {
        rc: s32 = 0;

        cpi.h_encoding_thread =
            cast(*Pthread_T) allocate_memory(
                size_of(Pthread_T) * cast,no_check(u64) th_count
            );

        if cpi.h_encoding_thread == null {
            internal_error(
                *cpi.common.error,
                cast,no_check(Codec_Err_T) CODEC_MEM_ERROR,
                c_string("Failed to allocate cpi->h_encoding_thread")
            );
        }
        cpi.h_event_start_encoding =
            cast(*Sem_T) allocate_memory(
                size_of(Sem_T) * cast,no_check(u64) th_count
            );

        if cpi.h_event_start_encoding == null {
            internal_error(
                *cpi.common.error,
                cast,no_check(Codec_Err_T) CODEC_MEM_ERROR,
                c_string("Failed to allocate cpi->h_event_start_encoding")
            );
        }
        cpi.h_event_end_encoding =
            cast(*Sem_T) allocate_memory(
                size_of(Sem_T) * cast,no_check(u64) th_count
            );

        if cpi.h_event_end_encoding == null {
            internal_error(
                *cpi.common.error,
                cast,no_check(Codec_Err_T) CODEC_MEM_ERROR,
                c_string("Failed to allocate cpi->h_event_end_encoding")
            );
        }
        cpi.mb_row_ei = cast(*MB_ROW_COMP) memalign(32, size_of(MB_ROW_COMP) * cast,no_check(u64) th_count);

        if cpi.mb_row_ei == null {
            internal_error(
                *cpi.common.error,
                cast,no_check(Codec_Err_T) CODEC_MEM_ERROR,
                c_string("Failed to allocate cpi->mb_row_ei")
            );
        }
        fill_memory(cpi.mb_row_ei, 0, size_of(MB_ROW_COMP) * cast,no_check(u64) th_count);
        cpi.en_thread_data =
            cast(*ENCODETHREAD_DATA) allocate_memory(
                size_of(ENCODETHREAD_DATA) * cast,no_check(u64) th_count
            );

        if cpi.en_thread_data == null {
            internal_error(
                *cpi.common.error,
                cast,no_check(Codec_Err_T) CODEC_MEM_ERROR,
                c_string("Failed to allocate cpi->en_thread_data")
            );
        }

        atomic_store_release_in_ethreading(*cpi.b_multi_threaded, 1);
        cpi.encoding_thread_count = th_count;

        ithread: s32 = 0;
        while ithread < th_count {
            ethd := *cpi.en_thread_data[ithread];

            vp8_setup_block_ptrs(*cpi.mb_row_ei[ithread].mb);
            vp8_setup_block_dptrs(*cpi.mb_row_ei[ithread].mb.e_mbd);

            sem_init(*(cast(*Sem_T) (cpi.h_event_start_encoding))[ithread], 0, 0);
            sem_init(*(cast(*Sem_T) (cpi.h_event_end_encoding))[ithread], 0, 0);

            ethd.ithread = ithread;
            ethd.ptr1 = cast(*void) cpi;
            ethd.ptr2 = cast(*void) (*cpi.mb_row_ei[ithread]);

            rc =
                c_transpiler_pthread_create(
                    *cpi.h_encoding_thread[ithread],
                    null,
                    cast,no_check(#type (_: *void) -> *void) thread_encoding_proc,
                    cast(*void) ethd
                );
            if rc != 0 {
                break;
            }
            ithread += 1;
        }

        if rc != 0 {
            atomic_store_release_in_ethreading(*cpi.b_multi_threaded, 0);
            ithread -= 1;
            while ithread >= 0 {
                sem_post(*(cast(*Sem_T) (cpi.h_event_start_encoding))[ithread]);
                sem_post(*(cast(*Sem_T) (cpi.h_event_end_encoding))[ithread]);
                pthread_join(cpi.h_encoding_thread[ithread], null);
                sem_destroy(*(cast(*Sem_T) (cpi.h_event_start_encoding))[ithread]);
                sem_destroy(*(cast(*Sem_T) (cpi.h_event_end_encoding))[ithread]);
                ithread -= 1;
            }

            deallocate_memory(cast(*void) cpi.h_event_start_encoding);
            cpi.h_event_start_encoding = null;
            deallocate_memory(cast(*void) cpi.h_event_end_encoding);
            cpi.h_event_end_encoding = null;
            deallocate_memory(cast(*void) cpi.h_encoding_thread);
            cpi.h_encoding_thread = null;
            deallocate_memory(cast(*void) cpi.mb_row_ei);
            cpi.mb_row_ei = null;
            deallocate_memory(cast(*void) cpi.en_thread_data);
            cpi.en_thread_data = null;
            cpi.encoding_thread_count = 0;

            return -1;
        }

        {
            lpfthd := *cpi.lpf_thread_data;

            sem_init(*cpi.h_event_start_lpf, 0, 0);
            sem_init(*cpi.h_event_end_lpf, 0, 0);

            lpfthd.ptr1 = cast(*void) cpi;
            rc =
                c_transpiler_pthread_create(
                    *cpi.h_filter_thread,
                    null,
                    cast,no_check(#type (_: *void) -> *void) thread_loopfilter,
                    cast(*void) lpfthd
                );

            if rc != 0 {
                atomic_store_release_in_ethreading(*cpi.b_multi_threaded, 0);
                ithread -= 1;
                while ithread >= 0 {
                    sem_post(*(cast(*Sem_T) (cpi.h_event_start_encoding))[ithread]);
                    sem_post(*(cast(*Sem_T) (cpi.h_event_end_encoding))[ithread]);
                    pthread_join(cpi.h_encoding_thread[ithread], null);
                    sem_destroy(*(cast(*Sem_T) (cpi.h_event_start_encoding))[ithread]);
                    sem_destroy(*(cast(*Sem_T) (cpi.h_event_end_encoding))[ithread]);
                    ithread -= 1;
                }
                sem_destroy(*cpi.h_event_end_lpf);
                sem_destroy(*cpi.h_event_start_lpf);

                deallocate_memory(cast(*void) cpi.h_event_start_encoding);
                cpi.h_event_start_encoding = null;
                deallocate_memory(cast(*void) cpi.h_event_end_encoding);
                cpi.h_event_end_encoding = null;
                deallocate_memory(cast(*void) cpi.h_encoding_thread);
                cpi.h_encoding_thread = null;
                deallocate_memory(cast(*void) cpi.mb_row_ei);
                cpi.mb_row_ei = null;
                deallocate_memory(cast(*void) cpi.en_thread_data);
                cpi.en_thread_data = null;
                cpi.encoding_thread_count = 0;

                return -2;
            }
        }
    }
    return 0;
}

thread_loopfilter :: (p_data: *void) -> *void {
    cpi := cast(*VP8_COMP) (cast(*LPFTHREAD_DATA) p_data).ptr1;
    cm := *cpi.common;

    while ((cast(s32) 1) != 0) {
        if atomic_load_acquire_in_ethreading(*cpi.b_multi_threaded) == 0 {
            break;
        }

        if vp8_sem_wait_in_ethreading(*cpi.h_event_start_lpf) == 0 {
            if atomic_load_acquire_in_ethreading(*cpi.b_multi_threaded) == 0 {
                break;
            }

            vp8_loopfilter_frame(cpi, cm);

            sem_post(*cpi.h_event_end_lpf);
        }
    }

    return null;
}

thread_encoding_proc :: (p_data: *void) -> *void {
    ithread := (cast(*ENCODETHREAD_DATA) p_data).ithread;
    cpi := cast(*VP8_COMP) (cast(*ENCODETHREAD_DATA) p_data).ptr1;
    mbri := cast(*MB_ROW_COMP) (cast(*ENCODETHREAD_DATA) p_data).ptr2;
    mb_row_left_context: ENTROPY_CONTEXT_PLANES = ---;

    while ((cast(s32) 1) != 0) {
        if atomic_load_acquire_in_ethreading(*cpi.b_multi_threaded) == 0 {
            break;
        }

        if vp8_sem_wait_in_ethreading(*(cast(*Sem_T) (cpi.h_event_start_encoding))[ithread]) == 0 {
            NSYNC := cpi.mt_sync_range;
            cm := *cpi.common;

            x := *mbri.mb;
            xd := *x.e_mbd;
            tp: *TOKENEXTRA = ---;

            segment_counts := mbri.segment_counts.data;
            totalrate := *mbri.totalrate;

            if atomic_load_acquire_in_ethreading(*cpi.b_multi_threaded) == 0 {
                break;
            }

            xd.mode_info_context = cm.mi + cm.mode_info_stride * (ithread + 1);
            xd.mode_info_stride = cm.mode_info_stride;

            mb_row := ithread + 1;
            while mb_row < cm.mb_rows {
                ref_fb_idx := cm.lst_fb_idx;
                dst_fb_idx := cm.new_fb_idx;
                recon_y_stride := cm.yv12_fb[ref_fb_idx].y_stride;
                recon_uv_stride := cm.yv12_fb[ref_fb_idx].uv_stride;
                map_index := mb_row * cm.mb_cols;

                current_mb_col := *(cast(*Atomic_Int) (cpi.mt_current_mb_col))[mb_row];

                tp = cpi.tok + mb_row * (cm.mb_cols * 16 * 24);
                cpi.tplist[mb_row].start = tp;

                last_row_current_mb_col := *(cast(*Atomic_Int) (cpi.mt_current_mb_col))[mb_row - 1];

                xd.above_context = cm.above_context;
                xd.left_context = *mb_row_left_context;

                fill_memory(*mb_row_left_context, 0, size_of(ENTROPY_CONTEXT_PLANES));

                xd.up_available = cast(s32) (mb_row != 0);
                recon_yoffset := mb_row * recon_y_stride * 16;
                recon_uvoffset := mb_row * recon_uv_stride * 8;

                x.mb_activity_ptr = *cpi.mb_activity_map[map_index];

                mb_col: s32 = 0;
                while mb_col < cm.mb_cols {
                    if (mb_col - 1) % NSYNC == 0 {
                        atomic_store_release_in_ethreading(current_mb_col, mb_col - 1);
                    }

                    if mb_row != 0 && mb_col & (NSYNC - 1) == 0 {
                        vp8_atomic_spin_wait_in_ethreading(mb_col, last_row_current_mb_col, NSYNC);
                    }

                    xd.mb_to_left_edge = -((mb_col * 16) << 3);
                    xd.mb_to_right_edge = ((cm.mb_cols - 1 - mb_col) * 16) << 3;
                    xd.mb_to_top_edge = -((mb_row * 16) << 3);
                    xd.mb_to_bottom_edge = ((cm.mb_rows - 1 - mb_row) * 16) << 3;

                    x.mv_col_min = -(mb_col * 16 + cast,no_check(s32) ((32 - 16)));
                    x.mv_col_max = (cm.mb_cols - 1 - mb_col) * 16 + cast,no_check(s32) ((32 - 16));
                    x.mv_row_min = -(mb_row * 16 + cast,no_check(s32) ((32 - 16)));
                    x.mv_row_max = (cm.mb_rows - 1 - mb_row) * 16 + cast,no_check(s32) ((32 - 16));

                    xd.dst.y_buffer = cm.yv12_fb[dst_fb_idx].y_buffer + recon_yoffset;
                    xd.dst.u_buffer = cm.yv12_fb[dst_fb_idx].u_buffer + recon_uvoffset;
                    xd.dst.v_buffer = cm.yv12_fb[dst_fb_idx].v_buffer + recon_uvoffset;
                    xd.left_available = cast(s32) (mb_col != 0);

                    x.rddiv = cpi.rddiv;
                    x.rdmult = cpi.rdmult;

                    vp8_copy_mem16x16_c(x.src.y_buffer, x.src.y_stride, x.thismb.data, 16);

                    if cpi.oxcf.tuning == cast,no_check(u32) VP8_TUNE_SSIM {
                        vp8_activity_masking(cpi, x);
                    }

                    if xd.segmentation_enabled != 0 {
                        if cpi.segmentation_map[map_index + mb_col] <= 3 {
                            xd.mode_info_context.mbmi.segment_id = cpi.segmentation_map[map_index + mb_col];
                        } else {
                            xd.mode_info_context.mbmi.segment_id = 0;
                        }

                        vp8cx_mb_init_quantizer(cpi, x, 1);
                    } else {
                        xd.mode_info_context.mbmi.segment_id = 0;
                    }

                    x.active_ptr = cpi.active_map + map_index + mb_col;

                    if cm.frame_type == cast,no_check(u32) KEY_FRAME_in_alloccommon {
                        totalrate.* += vp8cx_encode_intra_macroblock(cpi, x, *tp);
                    } else {
                        totalrate.* +=
                            vp8cx_encode_inter_macroblock(
                                cpi,
                                x,
                                *tp,
                                recon_yoffset,
                                recon_uvoffset,
                                mb_row,
                                mb_col
                            );

                        if cpi.current_layer == 0 {
                            if xd.mode_info_context.mbmi.mode == cast,no_check(u8) ZEROMV &&
                                xd.mode_info_context.mbmi.ref_frame == cast,no_check(u8) LAST_FRAME {
                                if cpi.consec_zero_last[map_index + mb_col] < 255 {
                                    cpi.consec_zero_last[map_index + mb_col] = cast,no_check(u8) ((cast,no_check(s32) cpi.consec_zero_last[map_index + mb_col]) + 1);
                                }
                                if cpi.consec_zero_last_mvbias[map_index + mb_col] < 255 {
                                    cpi.consec_zero_last_mvbias[map_index + mb_col] = cast,no_check(u8) ((cast,no_check(s32) cpi.consec_zero_last_mvbias[map_index + mb_col]) + 1);
                                }
                            } else {
                                cpi.consec_zero_last[map_index + mb_col] = 0;
                                cpi.consec_zero_last_mvbias[map_index + mb_col] = 0;
                            }
                            if x.zero_last_dot_suppress != 0 {
                                cpi.consec_zero_last_mvbias[map_index + mb_col] = 0;
                            }
                        }

                        if cpi.current_layer == 0 && cpi.cyclic_refresh_mode_enabled != 0 && xd.segmentation_enabled != 0 {
                            mbmi := *xd.mode_info_context.mbmi;
                            cpi.segmentation_map[map_index + mb_col] = mbmi.segment_id;

                            if mbmi.segment_id != 0 {
                                cpi.cyclic_refresh_map[map_index + mb_col] = -1;
                            } else if mbmi.mode == cast,no_check(u8) ZEROMV && mbmi.ref_frame == cast,no_check(u8) LAST_FRAME {
                                if cpi.cyclic_refresh_map[map_index + mb_col] == 1 {
                                    cpi.cyclic_refresh_map[map_index + mb_col] = 0;
                                }
                            } else {
                                cpi.cyclic_refresh_map[map_index + mb_col] = 1;
                            }
                        }
                    }

                    cpi.tplist[mb_row].stop = tp;

                    x.gf_active_ptr += 1;

                    x.mb_activity_ptr += 1;

                    x.src.y_buffer += 16;
                    x.src.u_buffer += 8;
                    x.src.v_buffer += 8;

                    recon_yoffset += 16;
                    recon_uvoffset += 8;

                    segment_counts[xd.mode_info_context.mbmi.segment_id] += 1;

                    xd.mode_info_context += 1;
                    x.partition_info += 1;
                    xd.above_context += 1;
                    mb_col += 1;
                }

                vp8_extend_mb_row(
                    cm.yv12_fb.data + dst_fb_idx,
                    xd.dst.y_buffer + 16,
                    xd.dst.u_buffer + 8,
                    xd.dst.v_buffer + 8
                );

                atomic_store_release_in_ethreading(current_mb_col, mb_col + NSYNC);

                xd.mode_info_context += 1;
                x.partition_info += 1;

                x.src.y_buffer += 16 * x.src.y_stride * (cpi.encoding_thread_count + 1) - 16 * cm.mb_cols;
                x.src.u_buffer += 8 * x.src.uv_stride * (cpi.encoding_thread_count + 1) - 8 * cm.mb_cols;
                x.src.v_buffer += 8 * x.src.uv_stride * (cpi.encoding_thread_count + 1) - 8 * cm.mb_cols;

                xd.mode_info_context += xd.mode_info_stride * cpi.encoding_thread_count;
                x.partition_info += xd.mode_info_stride * cpi.encoding_thread_count;
                x.gf_active_ptr += cm.mb_cols * cpi.encoding_thread_count;
                mb_row += cpi.encoding_thread_count + 1;
            }

            sem_post(*(cast(*Sem_T) (cpi.h_event_end_encoding))[ithread]);
        }
    }

    return null;
}

vp8cx_remove_encoder_threads :: (cpi: *VP8_COMP) {
    if atomic_load_acquire_in_ethreading(*cpi.b_multi_threaded) != 0 {
        atomic_store_release_in_ethreading(*cpi.b_multi_threaded, 0);
        {
            i: s32 = 0;
            while i < cpi.encoding_thread_count {
                sem_post(*(cast(*Sem_T) (cpi.h_event_start_encoding))[i]);
                sem_post(*(cast(*Sem_T) (cpi.h_event_end_encoding))[i]);

                pthread_join(cpi.h_encoding_thread[i], null);

                sem_destroy(*(cast(*Sem_T) (cpi.h_event_start_encoding))[i]);
                sem_destroy(*(cast(*Sem_T) (cpi.h_event_end_encoding))[i]);
                i += 1;
            }

            sem_post(*cpi.h_event_start_lpf);
            pthread_join(cpi.h_filter_thread, null);
        }

        sem_destroy(*cpi.h_event_end_lpf);
        sem_destroy(*cpi.h_event_start_lpf);
        cpi.b_lpf_running = 0;

        deallocate_memory(cast(*void) cpi.mt_current_mb_col);
        cpi.mt_current_mb_col = null;
        cpi.mt_current_mb_col_size = 0;
        deallocate_memory(cast(*void) cpi.h_event_start_encoding);
        cpi.h_event_start_encoding = null;
        deallocate_memory(cast(*void) cpi.h_event_end_encoding);
        cpi.h_event_end_encoding = null;
        deallocate_memory(cast(*void) cpi.h_encoding_thread);
        cpi.h_encoding_thread = null;
        deallocate_memory(cast(*void) cpi.mb_row_ei);
        cpi.mb_row_ei = null;
        deallocate_memory(cast(*void) cpi.en_thread_data);
        cpi.en_thread_data = null;
        cpi.encoding_thread_count = 0;
    }
}

sem_init :: (sem: *Sem_T, pshared: s32, value: u32) -> s32 #foreign System_Library_libc_so_6;

sem_destroy :: (sem: *Sem_T) -> s32 #foreign System_Library_libc_so_6;

